name: Unit Tests Runner

on: [push, pull_request]

jobs:
  unittests:
    name: Unit Tests Runner on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
        poetry-version: ['1.1.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Setup Python Poetry ${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Run Tests
        run: |
          poetry install
          poetry run pytest
